name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-docs:
    name: Publish docs
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Publish docs
        run: yarn publish-docs
